version: '2.1'
services:
  mapproxy:
    image: pdok/mapproxy
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
     - DEBUG=1
    volumes:
      - ./../config/mapproxy.yaml:/srv/mapproxy/config/mapproxy.yaml
      - ./../config/include.conf:/srv/mapproxy/config/include.conf
      - ./../config/lighttpd.auth:/srv/mapproxy/config/lighttpd.auth
    networks:
      mapproxy-exporter:
  exporter:
    image: lusotycoon/apache-exporter:v0.7.0
    restart: unless-stopped
    command: ["-scrape_uri=http://admin:admin@mapproxy/server-status?auto"]
    ports:
      - 9117:9117
    networks:
      mapproxy-exporter:     
networks:
  mapproxy-exporter:
